name: Test
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    env:
      IS_COVERAGE_ALLOWED: ${{ secrets.CODACY_PROJECT_TOKEN != '' }}
      IS_MASTER_BRANCH: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v1
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - run: npm install
    - name: Run linters
      run: |
        npm run lint
      env:
        CI: true
    - name: Run tests
      run: |
        if $IS_COVERAGE_ALLOWED && $IS_MASTER_BRANCH; then
            npm run test-with-coverage
            npm run upload-coverage
        else
            npm run test
        fi
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
